name: Django CI/CD Pipeline

on:
  push:
    branches: 
      - main  # Trigger the pipeline on pushes to the main branch
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install MySQL dependencies
        run: sudo apt-get install -y libmysqlclient-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Database
        env:
          DATABASE_URL: mysql://root:root@localhost:3306/test_db
        run: |
          python manage.py migrate
          python manage.py collectstatic --noinput

      - name: Run tests
        env:
          DATABASE_URL: mysql://root:root@localhost:3306/test_db
        run: |
          python manage.py test

      - name: Lint code
        run: |
          pip install flake8
          flake8 .
